### ISSUE TITLE
npm ERR! jpegtran-bin@0.2.0 postinstall: `node pre-build.js`

### ISSUE THREAD

**Issue by Tyvain** [DaftMonk/mean-chat#2]
```
npm WARN package.json chat@0.0.0 No repository field.
/
> jpegtran-bin@0.2.0 postinstall /home/dev.recif.nc/sylvain.auger-leger/mean-chat/node_modules/jpegtran-bin
> node pre-build.js


stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: connect EHOSTUNREACH
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)

npm ERR! jpegtran-bin@0.2.0 postinstall: `node pre-build.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the jpegtran-bin@0.2.0 postinstall script.
npm ERR! This is most likely a problem with the jpegtran-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node pre-build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls jpegtran-bin
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-44-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/dev.recif.nc/sylvain.auger-leger/mean-chat
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by Tyvain** [comment]
Fixed by replacing this in package.json : "jpegtran-bin": "latest",
