### ISSUE TITLE
Unknown provider: mySocketProvider <- mySocket <- chatroom

### ISSUE THREAD

**Issue by Tyvain** [DaftMonk/mean-chat#4]
```
Error: [$injector:unpr] Unknown provider: mySocketProvider <- mySocket <- chatroom
http://errors.angularjs.org/1.2.6/$injector/unpr?p0=mySocketProvider%20%3C-%20mySocket%20%3C-hatroom
    at http://localhost:9000/bower_components/angular/angular.js:78:12
    at http://localhost:9000/bower_components/angular/angular.js:3538:19
    at Object.getService [as get] (http://localhost:9000/bower_components/angular/angular.js:3665:39)
    at http://localhost:9000/bower_components/angular/angular.js:3543:45
    at getService (http://localhost:9000/bower_components/angular/angular.js:3665:39)
    at Object.invoke (http://localhost:9000/bower_components/angular/angular.js:3687:13)
    at http://localhost:9000/bower_components/angular/angular.js:3544:37
    at getService (http://localhost:9000/bower_components/angular/angular.js:3665:39)
    at invoke (http://localhost:9000/bower_components/angular/angular.js:3687:13)
    at Object.instantiate (http://localhost:9000/bower_components/angular/angular.js:3708:23)

```

**Comment by pCyril** [comment]
Do you find a way to fix it ?

**Comment by Tyvain** [comment]
Nope...

**Comment by dmmat** [comment]
@Tyvain emm... bug with register in unix os, change 

```
    <script src="scripts/services/mySocket.js"></script>
    <script src="scripts/directives/autoScroll.js"></script>
    ...
    <script src="scripts/directives/historyBack.js"></script>
```

to

```
    <script src="scripts/services/mysocket.js"></script>
    <script src="scripts/directives/autoscroll.js"></script>        
    ...
    <script src="scripts/directives/historyback.js"></script>
```

in app/views/index.html
